function rHealth(){
  let h=rHdr('Health','Medication, sleep, exercise, and refill tracking');
  const sleepItems=X.sleepLogs.slice().reverse().slice(0,7).map((s,i)=>({label:['S','M','T','W','T','F','S'][i]||String(i+1),value:getSleepHours(s)})).reverse();
  const sleepAvg=getAvgSleepHours();
  const refillSoon=X.medications.map(m=>({m,...getMedicationRefillStatus(m)})).filter(x=>x.urgent);
  const exerciseWeek=X.exerciseLogs.filter(x=>new Date(x.date)>=new Date(Date.now()-7*86400000)).reduce((a,x)=>a+(Number(x.minutes)||0),0);
  h+=`<div class="panel"><h3>Medication tracker</h3><div class="safe-row"><button class="xbtn" onclick="addMedication()">+ Medication</button><button class="xbtn" onclick="logDose()">💊 Log dose</button><button class="xbtn" onclick="syncMedicationReminders()">⏰ Sync reminders</button></div>${X.medications.map(m=>{const st=getMedicationRefillStatus(m);return `<div class="list-row"><div class="list-main"><b>${esc(m.name)}${m.dose?` · ${esc(m.dose)}`:''}</b><span>${esc(st.text)}${m.times?.length?` · ${esc(m.times.join(', '))}`:''}</span></div><div style="display:flex;gap:6px"><button class="cact" onclick="editMedication('${m.id}')">✏️</button><button class="cact" onclick="deleteMedication('${m.id}')">🗑</button></div></div>`}).join('')||'<div class="sdesc">No medications tracked yet.</div>'}${refillSoon.length?`<div class="mini-list" style="margin-top:10px">${refillSoon.map(x=>`<div class="mini-item">⚠️ ${esc(x.m.name)} · ${esc(x.text)}</div>`).join('')}</div>`:''}</div>`;
  h+=`<div class="panel"><h3>Sleep log</h3><div class="dash-big" style="font-size:30px">${sleepAvg?`${sleepAvg.toFixed(1)}h`:'—'}</div><div class="sdesc">Average from recent logs</div>${renderMiniBars(sleepItems,8)}<div class="safe-row"><button class="xbtn" onclick="addSleepLog()">+ Sleep entry</button></div>${X.sleepLogs.slice().reverse().slice(0,6).map(s=>`<div class="list-row"><div class="list-main"><b>${new Date(s.date).toLocaleDateString()}</b><span>Bed ${esc(s.bed)} · Wake ${esc(s.wake)} · ${getSleepHours(s).toFixed(1)}h</span></div><div style="display:flex;gap:6px"><button class="cact" onclick="editSleepLog('${s.id}')">✏️</button><button class="cact" onclick="deleteSleepLog('${s.id}')">🗑</button></div></div>`).join('')||''}</div>`;
  h+=`<div class="panel"><h3>Exercise tracker</h3><div class="dash-big" style="font-size:30px">${exerciseWeek} min</div><div class="sdesc">Last 7 days</div><div class="safe-row"><button class="xbtn" onclick="addExerciseLog()">+ Exercise</button></div>${X.exerciseLogs.slice().reverse().slice(0,6).map(s=>`<div class="list-row"><div class="list-main"><b>${esc(s.type)}</b><span>${s.minutes} min · ${new Date(s.date).toLocaleDateString()}</span></div><div style="display:flex;gap:6px"><button class="cact" onclick="editExerciseLog('${s.id}')">✏️</button><button class="cact" onclick="deleteExerciseLog('${s.id}')">🗑</button></div></div>`).join('')||'<div class="sdesc">No exercise logged yet.</div>'}</div>`;
  h+=`<div class="panel"><h3>Dose history</h3>${X.medicationLogs.slice().reverse().slice(0,8).map(x=>`<div class="list-row"><div class="list-main"><b>${esc((X.medications.find(m=>m.id===x.medId)||{}).name||'Medication')}</b><span>${new Date(x.date).toLocaleString()}${x.dose?` · ${esc(x.dose)}`:''}${x.childId?` · ${esc(getChildName(x.childId))}`:''}</span></div></div>`).join('')||'<div class="sdesc">No doses logged yet.</div>'}</div>`;
  return h;
}
function openHealthQuickAdd(){const ov=document.createElement('div');ov.className='mo';ov.onclick=e=>{if(e.target===ov)ov.remove()};ov.innerHTML=`<div class="mo-in" onclick="event.stopPropagation()"><div class="mo-h"></div><h3>Health quick add</h3><div class="snz-opt" onclick="addMedication();this.closest('.mo').remove()">💊 Add medication</div><div class="snz-opt" onclick="logDose();this.closest('.mo').remove()">📝 Log dose</div><div class="snz-opt" onclick="addSleepLog();this.closest('.mo').remove()">😴 Add sleep entry</div><div class="snz-opt" onclick="addExerciseLog();this.closest('.mo').remove()">🏃 Add exercise</div></div>`;document.body.appendChild(ov)}
function addMedication(){openMedicationForm()}
function logDose(){if(!X.medications.length){showToast('Add a medication first');return;}openRecordModal({title:'Log medication dose',fields:[{name:'medId',label:'Medication',type:'select',value:X.medications[0]?.id||'',options:X.medications.map(m=>({value:m.id,label:m.name}))},{name:'childId',label:'Child / person',type:'select',value:activeKidId||'',options:[{value:'',label:'General / not child-specific'},...X.children.map(c=>({value:c.id,label:c.name}))]},{name:'dose',label:'Dose',value:X.medications[0]?.dose||''}],onSubmit:(vals)=>{const med=X.medications.find(m=>m.id===vals.medId)||X.medications[0];if(!med)return false;X.medicationLogs.unshift({id:gid(),medId:med.id,date:new Date().toISOString(),dose:(vals.dose||med.dose||'').trim(),childId:vals.childId||''});const refillSoon=med.refillDate&&new Date(med.refillDate)-new Date()<14*86400000;sv();render();showToast(refillSoon?'Dose logged · refill due soon':'Dose logged');return true;}})}
function addSleepLog(){openSleepLogForm()}
function addExerciseLog(){openExerciseLogForm()}
function getAvgSleepHours(){const vals=X.sleepLogs.map(s=>{if(!s.bed||!s.wake)return null;const [bh,bm]=s.bed.split(':').map(Number),[wh,wm]=s.wake.split(':').map(Number);if([bh,bm,wh,wm].some(Number.isNaN))return null;let mins=(wh*60+wm)-(bh*60+bm);if(mins<=0)mins+=24*60;return mins/60;}).filter(v=>v!=null);if(!vals.length)return 0;return vals.reduce((a,v)=>a+v,0)/vals.length}
function rMoney(){
  let h=rHdr('Budget & Money','Bills, expenses, income, contributions');
  const monthKey=fmtLD(new Date()).slice(0,7);
  const billActive=R.filter(r=>!r.completed&&r.category==='bills');
  const billTotal=billActive.reduce((a,r)=>a+(Number(r.amount)||0),0);
  const paidBills=getPaidBills(monthKey);
  const paidTotal=paidBills.reduce((a,r)=>a+(Number(r.amount)||0),0);
  const monthExpenses=(X.expenses||[]).filter(e=>String(e.date).startsWith(monthKey));
  const expenseTotal=monthExpenses.reduce((a,e)=>a+(Number(e.amount)||0),0);
  const totalSpent=paidTotal+expenseTotal;
  const incomeThisMonth=(X.incomes||[]).filter(i=>String(i.date).startsWith(monthKey));
  const incomeTotal=incomeThisMonth.reduce((a,i)=>a+(Number(i.amount)||0),0);
  const templatesOnly=(X.shoppingLists||[]).filter(l=>l.template);
  const catActuals=getMoneyCategoryActuals(monthKey);
  const deadlines=getContributionDeadlineSummary();
  const paycheckRows=getPaycheckCalendarRows(4);
  // Expense by category
  const expByCat={};monthExpenses.forEach(e=>{expByCat[e.category]=(expByCat[e.category]||0)+e.amount});
  h+=`<div class="dash-grid" style="padding-bottom:0"><div class="dash-card" onclick="logExpense()" style="cursor:pointer"><div class="dash-title">🧾 Log Expense</div><div class="dash-big" style="font-size:20px">Tap to add</div></div><div class="dash-card"><div class="dash-title">Total spent</div><div class="dash-big">$${totalSpent.toFixed(0)}</div><div class="dash-sub">Bills $${paidTotal.toFixed(0)} + Other $${expenseTotal.toFixed(0)}</div></div><div class="dash-card"><div class="dash-title">Upcoming bills</div><div class="dash-big">$${billTotal.toFixed(0)}</div><div class="dash-sub">${billActive.length} open</div></div><div class="dash-card"><div class="dash-title">Net this month</div><div class="dash-big" style="color:${incomeTotal-totalSpent>=0?'var(--green)':'var(--red)'}">$${(incomeTotal-totalSpent).toFixed(0)}</div><div class="dash-sub">Income $${incomeTotal.toFixed(0)}</div></div></div>`;
  // Expense history
  h+=`<div class="panel"><h3>Recent expenses</h3><div class="safe-row"><button class="xbtn" onclick="logExpense()">+ Log Expense</button></div>${monthExpenses.slice(0,10).map(e=>`<div class="list-row"><div class="list-main"><b>${esc(e.title)}</b><span>${esc(e.category)} · ${new Date(e.date).toLocaleDateString()} · $${Number(e.amount).toFixed(2)}</span></div><button class="cact" onclick="deleteExpense('${e.id}')">🗑</button></div>`).join('')||'<div class="sdesc">No expenses logged this month. Tap + to start.</div>'}${Object.keys(expByCat).length?`<div style="margin-top:10px">${Object.entries(expByCat).sort((a,b)=>b[1]-a[1]).map(([cat,amt])=>`<div class="mini-item">${esc(cat)}: $${amt.toFixed(2)}</div>`).join('')}</div>`:''}</div>`;
  h+=`<div class="panel"><h3>Budget categories</h3><div class="safe-row"><button class="xbtn" onclick="addBudgetCategory()">+ Category</button><button class="xbtn" onclick="addIncomeEntry()">+ Income</button><button class="xbtn" onclick="addContribution()">+ RRSP/RESP</button></div>${catActuals.map(b=>{const pct=b.budget?Math.min(100,Math.round((b.actual/b.budget)*100)):0;return `<div class="list-row"><div class="list-main"><b>${esc(b.name)}</b><span>Budget $${Number(b.budget).toFixed(0)} · Actual $${Number(b.actual).toFixed(0)}${b.budget?` · ${pct}%`:''}</span></div><div style="display:flex;gap:6px"><button class="cact" onclick="editBudgetCategory('${b.id}')">✏️</button><button class="cact" onclick="deleteBudgetCategory('${b.id}')">🗑</button></div></div>`}).join('')||'<div class="sdesc">No budget categories yet.</div>'}</div>`;
  const payInfo=getPayCycleInfo(new Date());
  h+=`<div class="panel"><h3>Paycheck calendar</h3><div class="mini-item">Anchor: ${fmtLD(payInfo.anchor)} · Current cycle: ${fmtLD(payInfo.currentStart)} → ${fmtLD(payInfo.currentEnd)}</div><div class="safe-row"><button class="xbtn" onclick="openPaycheckCalendar()">📅 Open full calendar</button><button class="xbtn" onclick="setPayAnchor()">⚙️ Set anchor</button></div>${paycheckRows.map(r=>`<div class="list-row"><div class="list-main"><b>Pay ${new Date(r.payDate+'T00:00').toLocaleDateString()}</b><span>${r.periodStart} → ${r.periodEnd} · ${r.hours.toFixed(1)}h${r.overtime?` · OT ${r.overtime.toFixed(1)}h`:''}</span></div></div>`).join('')}</div>`;
  h+=`<div class="panel"><h3>Income vs expenses</h3>${incomeThisMonth.slice(0,6).map(c=>`<div class="list-row"><div class="list-main"><b>${esc(c.title)} · $${Number(c.amount).toFixed(2)}</b><span>${new Date(c.date).toLocaleDateString()}</span></div><div style="display:flex;gap:6px"><button class="cact" onclick="editIncomeEntry('${c.id}')">✏️</button><button class="cact" onclick="deleteIncomeEntry('${c.id}')">🗑</button></div></div>`).join('')||'<div class="sdesc">No income logged this month yet.</div>'}<div class="mini-item">Monthly net: $${(incomeTotal-paidTotal).toFixed(2)}</div></div>`;
  h+=`<div class="panel"><h3>Already paid history</h3>${paidBills.slice(0,8).map(c=>`<div class="list-row"><div class="list-main"><b>${esc(c.title)}</b><span>${new Date(c.completedAt).toLocaleDateString()}${c.amount?` · $${Number(c.amount).toFixed(2)}`:''}</span></div></div>`).join('')||'<div class="sdesc">No paid bills this month yet.</div>'}</div>`;
  h+=`<div class="panel"><h3>Contribution tracker</h3><div class="mini-list"><div class="mini-item">RRSP YTD: $${deadlines.rrspTotal.toFixed(2)} · deadline ${deadlines.rrspDeadline.toLocaleDateString()}</div><div class="mini-item">RESP YTD: $${deadlines.respTotal.toFixed(2)} · remaining to $${deadlines.respTarget}: $${deadlines.respRemaining.toFixed(2)}</div></div>${X.contributionLogs.slice().reverse().slice(0,8).map(c=>`<div class="list-row"><div class="list-main"><b>${esc(c.type)} · $${Number(c.amount).toFixed(2)}</b><span>${new Date(c.date).toLocaleDateString()}${c.notes?` · ${esc(c.notes)}`:''}</span></div><div style="display:flex;gap:6px"><button class="cact" onclick="editContribution('${c.id}')">✏️</button><button class="cact" onclick="deleteContribution('${c.id}')">🗑</button></div></div>`).join('')||'<div class="sdesc">No contributions logged yet.</div>'}</div>`;
  h+=`<div class="panel"><h3>Shopping list</h3><div class="safe-row"><button class="xbtn" onclick="addShoppingItem()">+ Item</button><button class="xbtn" onclick="addShoppingTemplate()">📋 Save template</button><button class="xbtn" onclick="openChecklistShare()">📤 Share / QR</button></div>${(X.shoppingLists[0]?.items||[]).map(it=>`<div class="list-row"><div class="list-main"><b>${it.done?'✓ ':'○ '}${esc(it.text)}</b></div><button class="cact" onclick="toggleShoppingItem('${it.id}')">${it.done?'✅':'⬜'}</button></div>`).join('')||'<div class="sdesc">Shopping list is empty.</div>'}${templatesOnly.length?`<div class="mini-list" style="margin-top:10px">${templatesOnly.slice(0,5).map(t=>`<div class="mini-item"><b>${esc(t.name)}</b> · ${t.items.length} items <button class="chip-btn" onclick="applyShoppingTemplate('${t.id}')">Apply</button></div>`).join('')}</div>`:''}</div>`;
  h+=`<div class="panel"><h3>Home maintenance</h3><div class="safe-row"><button class="xbtn" onclick="createMaintenanceReminder('maintenance')">+ Maintenance task</button><button class="xbtn" onclick="createMaintenanceReminder('seasonal')">+ Seasonal task</button><button class="xbtn" onclick="addSeasonalReminder()">🌦 Saved seasonal</button></div>${X.seasonalReminders.slice(0,6).map(v=>`<div class="list-row"><div class="list-main"><b>${esc(v.title)}</b><span>${new Date(new Date().getFullYear(),v.month,v.day).toLocaleDateString([],{month:'short',day:'numeric'})}${v.notes?` · ${esc(v.notes)}`:''}</span></div><div style="display:flex;gap:6px"><button class="cact" onclick="materializeSeasonalReminder('${v.id}')">＋</button><button class="cact" onclick="editSeasonalReminder('${v.id}')">✏️</button><button class="cact" onclick="deleteSeasonalReminder('${v.id}')">🗑</button></div></div>`).join('')||'<div class="sdesc">No seasonal reminders yet.</div>'}</div>`;
  h+=`<div class="panel"><h3>Vehicle maintenance</h3><div class="safe-row"><button class="xbtn" onclick="addVehicleLog()">+ Service log</button></div>${X.vehicleLogs.slice().reverse().slice(0,6).map(v=>`<div class="list-row"><div class="list-main"><b>${esc(v.title)}</b><span>${new Date(v.date).toLocaleDateString()}${v.odometer?` · ${esc(v.odometer)} km`:''}${v.notes?` · ${esc(v.notes)}`:''}</span></div><div style="display:flex;gap:6px"><button class="cact" onclick="editVehicleEntry('${v.id}')">✏️</button><button class="cact" onclick="deleteVehicleEntry('${v.id}')">🗑</button></div></div>`).join('')||'<div class="sdesc">No vehicle logs yet.</div>'}</div>`;
  return h;
}
function openMoneyQuickAdd(){const ov=document.createElement('div');ov.className='mo';ov.onclick=e=>{if(e.target===ov)ov.remove()};ov.innerHTML=`<div class="mo-in" onclick="event.stopPropagation()"><div class="mo-h"></div><h3>Money quick add</h3><div class="snz-opt" onclick="quickAddBill();this.closest('.mo').remove()">💰 Add bill</div><div class="snz-opt" onclick="logExpense();this.closest('.mo').remove()">🧾 Log expense</div><div class="snz-opt" onclick="addIncomeEntry();this.closest('.mo').remove()">💵 Add income</div><div class="snz-opt" onclick="addContribution();this.closest('.mo').remove()">🏦 Add RRSP/RESP</div><div class="snz-opt" onclick="addBudgetCategory();this.closest('.mo').remove()">🧮 Add budget category</div><div class="snz-opt" onclick="addShoppingItem();this.closest('.mo').remove()">🛒 Add shopping item</div><div class="snz-opt" onclick="addVehicleLog();this.closest('.mo').remove()">🚗 Add vehicle service log</div></div>`;document.body.appendChild(ov)}
function logExpense(){
  const cats=['Groceries','Gas','Kids','Dining','Transport','Shopping','Bills','Health','Other'];
  openRecordModal({title:'Log expense',submitHint:'Saves this expense in your current month log.',fields:[
    {name:'title',label:'What did you spend on?',value:'',required:true,placeholder:'FreshCo groceries'},
    {name:'amount',label:'Amount ($)',type:'number',value:'',required:true,placeholder:'85.00'},
    {name:'category',label:'Category',type:'select',options:cats.map(c=>({value:c,label:c})),value:'Groceries'}
  ],onSubmit:(vals)=>{
    const title=(vals.title||'').trim();const amount=Number(vals.amount)||0;
    if(!title){showToast('Enter a description');return false;}
    if(!amount||amount<=0){showToast('Enter an amount');return false;}
    X.expenses.unshift({id:gid(),title,amount,category:vals.category||'Other',date:new Date().toISOString()});
    logAction('expense',`Logged $${amount.toFixed(2)} — ${title}`);
    sv();render();showToast(`$${amount.toFixed(2)} logged`);return true;
  }});
}
function deleteExpense(id){X.expenses=X.expenses.filter(e=>e.id!==id);sv();render();showToast('Expense removed')}
function addBudgetCategory(){openBudgetCategoryForm()}
function addIncomeEntry(){openIncomeEntryForm()}
function addContribution(){openContributionForm()}
function addShoppingItem(){openRecordModal({title:'Add shopping item',fields:[{name:'text',label:'Item',value:'',required:true}],onSubmit:(vals)=>{const text=vals.text.trim();if(!text)return false;X.shoppingLists[0].items.push({id:gid(),text,done:false});sv();render();return true;}})}
function toggleShoppingItem(id){const item=X.shoppingLists[0]?.items.find(x=>x.id===id);if(!item)return;item.done=!item.done;sv();render();}
async function shareShoppingList(){openChecklistShare()}
function addVehicleLog(){openVehicleLogForm()}
