function rMyDay(){
  let h=rHdr('My Day','Focus on what matters');if(ttActive)h+=rTTActive();
  const tasks=R.filter(r=>!r.completed&&(isToday(r.dueDate)||urg(r.dueDate)==='overdue')).sort((a,b)=>((isInTop3(b.id)?1:0)-(isInTop3(a.id)?1:0))||new Date(a.dueDate)-new Date(b.dueDate));
  const plan=buildProductivityPlan({scopedToday:true});
  const grouped={morning:[],afternoon:[],evening:[],any:[]};
  tasks.forEach(r=>{const key=r.bundle||'any';(grouped[key]||grouped.any).push(r)});
  h+=`<div class="prod-toolbar"><div class="prod-row"><button class="xbtn" onclick="openTop3Picker()">⭐ Pick top 3</button><button class="xbtn" onclick="openPowerHourPlan()">⚡ Build next block</button><button class="xbtn" onclick="openRecoveryPlan()">🧹 Reset pile</button></div><div class="prod-row"><span class="lane-pill${X.energyLevel==='low'?' on':''}" onclick="setEnergyLevel('low')">Low energy</span><span class="lane-pill${X.energyLevel==='normal'?' on':''}" onclick="setEnergyLevel('normal')">Normal</span><span class="lane-pill${X.energyLevel==='high'?' on':''}" onclick="setEnergyLevel('high')">High energy</span></div><div class="prod-row"><span class="lane-pill${Number(X.availableMinutes||30)===15?' on':''}" onclick="setAvailableMinutes(15)">15 min</span><span class="lane-pill${Number(X.availableMinutes||30)===30?' on':''}" onclick="setAvailableMinutes(30)">30 min</span><span class="lane-pill${Number(X.availableMinutes||30)===60?' on':''}" onclick="setAvailableMinutes(60)">60 min</span><span class="lane-pill${Number(X.availableMinutes||30)===90?' on':''}" onclick="setAvailableMinutes(90)">90 min</span></div><div class="prod-row"><span class="lane-pill${X.focusStyle==='balanced'?' on':''}" onclick="setFocusStyle('balanced')">Balanced</span><span class="lane-pill${X.focusStyle==='quick'?' on':''}" onclick="setFocusStyle('quick')">Quick wins</span><span class="lane-pill${X.focusStyle==='deep'?' on':''}" onclick="setFocusStyle('deep')">Deep work</span><span class="lane-pill${X.focusStyle==='admin'?' on':''}" onclick="setFocusStyle('admin')">Admin</span></div></div>`;
  h+=`<div style="padding:0 14px"><div class="prod-kpis"><div class="prod-kpi" onclick="filter='overdue';go('tasks')" style="cursor:pointer"><b>${plan.stats.overdue}</b><span>Overdue</span></div><div class="prod-kpi" onclick="filter='all';go('tasks')" style="cursor:pointer"><b>${plan.stats.fit}</b><span>Fit this window</span></div><div class="prod-kpi" onclick="filter='all';go('tasks')" style="cursor:pointer"><b>${plan.queue.length}</b><span>In your queue</span></div></div></div>`;
  h+=`<div class="coach-banner"><h3>${esc(plan.coach.title)}</h3><p>${esc(plan.coach.body)}</p><div class="hero-actions"><button class="chip-btn" onclick="go('whatnow')">What should I do?</button><button class="chip-btn" onclick="openPowerHourPlan()">Open plan</button></div></div>`;
  if(plan.queue.length)h+=`<div class="panel"><h3>Next ${plan.minutes} minutes</h3><div class="focus-queue">${plan.queue.map((task,i)=>`<div class="focus-step"><b>${i+1}. ${esc(task.title)}</b><span>${task.effort} min · ${esc(task.reasons.join(' • ')||'good fit')}</span><div class="safe-row" style="margin-top:8px"><button class="chip-btn" onclick="openFocus('${task.id}')">Focus</button><button class="chip-btn" onclick="toggleComp('${task.id}')">Done</button></div></div>`).join('')}</div></div>`;
  h+=`<div class="plan-grid" style="padding:0 14px 4px"><div class="plan-card"><h4>Quick wins</h4>${plan.quickWins.length?plan.quickWins.map(task=>`<div class="queue-line"><div><b>${esc(task.title)}</b><span>${esc(getCategory(task.category).label)} · ${esc(task.reasons[0]||'fast win')}</span></div><div class="queue-min">${task.effort}m</div></div>`).join(''):'<div class="sdesc">No clear quick wins.</div>'}</div><div class="plan-card"><h4>Deep work</h4>${plan.deepWork.length?plan.deepWork.map(task=>`<div class="queue-line"><div><b>${esc(task.title)}</b><span>${esc(getCategory(task.category).label)} · best ${task.bestDay}</span></div><div class="queue-min">${task.effort}m</div></div>`).join(''):'<div class="sdesc">Nothing heavy needs your brain right now.</div>'}</div></div>`;
  if(plan.batches.length)h+=`<div class="panel"><h3>Batch together</h3>${plan.batches.map(group=>`<div class="list-row"><div class="list-main"><b>${esc(group.icon)} ${esc(group.label)}</b><span>${group.items.map(t=>t.title).join(' · ')}</span></div></div>`).join('')}</div>`;
  h+=`<div class="clist compact-cards" style="padding-top:2px">`;
  [['morning','🌅 Morning'],['afternoon','☀️ Afternoon'],['evening','🌙 Evening'],['any','📌 Anytime']].forEach(([key,label])=>{if(grouped[key].length)h+=`<div class="panel" style="margin:0 14px 10px"><h3 style="margin-bottom:10px">${label}</h3>${rCards(grouped[key])}</div>`});
  if(!tasks.length)h+=`<div class="empty"><div class="empty-i">🌤️</div><div class="empty-t">Nothing scheduled for today</div></div>`;
  h+=`</div>`;return h;
}
function openTop3Picker(){const ov=document.createElement('div');ov.className='mo';ov.onclick=e=>{if(e.target===ov){ov.remove();render()}};ov.id='top3M';ov.innerHTML=`<div class="mo-in" onclick="event.stopPropagation()"><div class="mo-h"></div><h3>Pick your top 3 for today</h3><div id="top3List"></div><button class="sbtn" onclick="document.getElementById('top3M').remove();render()">Close</button></div>`;document.body.appendChild(ov);refreshTop3Modal()}
function refreshTop3Modal(){const el=document.getElementById('top3List');if(!el)return;const tasks=R.filter(r=>!r.completed&&(isToday(r.dueDate)||urg(r.dueDate)==='overdue')).sort((a,b)=>new Date(a.dueDate)-new Date(b.dueDate));el.innerHTML=tasks.map(r=>`<div class="snz-opt" onclick="toggleTop3('${r.id}')">${isInTop3(r.id)?'✅':'⬜'} ${esc(r.title)}</div>`).join('')||'<div class="empty"><div class="empty-t">No tasks due today</div></div>';}
function openFocus(id){const r=R.find(x=>x.id===id);if(!r)return;const ov=document.createElement('div');ov.className='focus-ov';ov.id='focusOv';ov.innerHTML=`<div style="font-size:18px;color:var(--text3);font-weight:700">Focus mode</div><div class="focus-title">${esc(r.title)}</div>${r.notes?`<div class="focus-notes">${esc(r.notes)}</div>`:''}${r.subtasks?.length?`<div class="panel" style="margin:0 auto 18px;max-width:340px;text-align:left">${r.subtasks.map((s,i)=>`<div class="csub${s.done?' dn':''}"><button class="csubchk${s.done?' on':''}" onclick="toggleSub('${r.id}',${i});openFocus('${r.id}')">${s.done?'✓':''}</button><span>${esc(s.text)}</span></div>`).join('')}</div>`:''}<div class="focus-actions"><button style="background:var(--green);color:#fff" onclick="toggleComp('${r.id}');document.getElementById('focusOv').remove()">✓ Done</button><button style="background:var(--accent);color:#fff" onclick="startPomo('${r.id}')">🍅 Pomodoro</button><button style="background:var(--bg3);color:var(--text2)" onclick="document.getElementById('focusOv').remove()">Close</button></div>`;document.body.appendChild(ov)}
function rHabits(){
  let h=rHdr('Habits','Custom goals and streaks');
  h+=`<div style="padding:10px 14px"><div class="frow"><input id="habIn" placeholder="New habit..." style="margin:0"><select id="habGoal"><option value="daily">Daily goal</option><option value="weekly">Weekly goal</option></select><select id="habTarget"><option value="1">1x</option><option value="2">2x</option><option value="3">3x</option><option value="4">4x</option><option value="5">5x</option><option value="6">6x</option><option value="7">7x</option></select></div><button class="xbtn" onclick="addHabitEnhanced()">+ Add Habit</button></div>`;
  const today=new Date(),days=[];for(let i=6;i>=0;i--){const d=new Date(today);d.setDate(d.getDate()-i);days.push(d)}
  h+=`<div style="padding:0 14px 72px">`;
  habits.forEach((hab,hi)=>{const countThisWeek=days.filter(d=>hab.log.includes(d.toDateString())).length;const goalTxt=hab.goalType==='weekly'?`${countThisWeek}/${hab.target} this week`:`Daily`;h+=`<div class="habit-card"><div class="habit-top"><span class="habit-name">${esc(hab.name)}</span><span class="habit-streak">🔥 ${getHabitStreak(hab)}d</span></div><div style="font-size:11px;color:var(--text3);margin-bottom:8px">${goalTxt}</div><div class="habit-days">${days.map(d=>{const ds=d.toDateString(),done=hab.log&&hab.log.includes(ds),isT=d.toDateString()===today.toDateString();return`<button class="habit-day${done?' done':''}${isT?' today':''}" onclick="toggleHabit(${hi},'${ds}')">${d.toLocaleDateString([],{weekday:'narrow'})}</button>`}).join('')}</div></div>`});
  h+=`</div>`;return h;
}
function addHabitEnhanced(){const inp=document.getElementById('habIn');if(!inp||!inp.value.trim())return;habits.push({id:gid(),name:inp.value.trim(),log:[],goalType:document.getElementById('habGoal')?.value||'daily',target:Number(document.getElementById('habTarget')?.value||1)});logAction('habit',`Added habit ${inp.value.trim()}`);sv();render();}

function groupActionLogByDay(limitDays=14){
  const groups={};
  (X.actionLog||[]).slice().reverse().forEach(a=>{
    const key=fmtLD(new Date(a.date));
    if(!groups[key])groups[key]=[];
    if(groups[key].length<12)groups[key].push(a);
  });
  return Object.entries(groups).sort((a,b)=>b[0].localeCompare(a[0])).slice(0,limitDays);
}
